version: "3.9"
services:
  development-environment:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes: 
      - ./scripts:/clumsy-graphics/scripts
      - ./source:/clumsy-graphics/source
      - ./__tests__:/clumsy-graphics/__tests__
      - ./example-project:/clumsy-graphics/example-project