version: "3.9"
services:
  clumsy-graphics:
    build: 
      context: .
      dockerfile: clumsy-graphics-package.Dockerfile
    environment:
      - ANIMATION_MODULE_PATH=${ANIMATION_MODULE_PATH}
      - CLIENT_SERVER_PORT=${CLIENT_SERVER_PORT}
    volumes: 
      - ${PROJECT_DIRECTORY_PATH}:/clumsy-graphics