version: "3.9"
services:
  development-environment:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes: 
      - ./scripts:/graphics-renderer/scripts
      - ./source:/graphics-renderer/source
      - ./__tests__:/graphics-renderer/__tests__
      - ./example-project:/graphics-renderer/example-project